use_frameworks!

platform :ios, '8.0'

target 'LiuChaoYangNetWork_Example' do
  pod 'LiuChaoYangNetWork', :path => '../'

  target 'LiuChaoYangNetWork_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
